version: "2.2"
services:
  ubuntu:
    image: ubuntu:18.04
    build:
      context: .
      dockerfile: dockerfile-ubuntu
    image: ubuntu:latest
    container_name: zpy
    tty: true
    volumes:
      - "./src:/zpy"
    cap_add:
      - SYS_PTRACE
